### ISSUE TITLE
Detect missing JavaFX

### ISSUE THREAD

**Issue by Arkanosis** [fthevenet/binjr#1]
Spotted by @rgroux: launching binjr without JavaFX results in an unhelpful error message: “Error: Could not find or load main class eu.fthevenet.binjr.Main”.

I guess that could be improved by detecting whether JavaFX is available or not, and by asking the user to install JavaFX in the latter case.

**Comment by fthevenet** [comment]
This is a fair point, but unfortunately there is no trivial way to do that; initializing JFX requires that the main class inherits from **javafx**.application.Application, so even on entering the main method it is already too late to do anything.

An obvious workaround would be to do that check in a bootstrap of some kind, but that would break the "single jar" philosophy.
Going down that road, the best approach could well be to use JavaFX built-in ability to package the app with its own copy of the jre as a platform dependent installation package( msi, rpm, dmg).
This would solve all of the runtime dependency issues, but you'd trade a 5 MB executable for 70MB installer.

**Comment by fthevenet** [comment]
OK, so I've found a way to create platform specific bundles as part of the maven build workflow, which makes it *almost*  painless to propose these as downloads for each release.
Well almost because you can't crossbuild native bundles, so build must be run on each of the supported platforms for every release, which is a massive pain (and even simply out of my reach in the case of MacOS).

So before I bother, anyone care to comment on whether that effectively feels useful or not?

**Comment by Arkanosis** [comment]
Once you know the issue is JavaFX, it doesn't feel like something critical, but for a first attempt to use a yet unknown program, it's definitely causing some friction.

At Labsquare and REGOVAR, we rely on Travis and AppVeyor to automate Linux and Windows builds, respectively. Both are free for open-source projects. I wonder if Travis couldn't build for MacOS as well.

**Comment by fthevenet** [comment]
I don't think any free service propose automate builds for MacOS given that, AFAIK, its licence explicitly forbids running it on a virtual machine or non Apple-made HW.
And I don't see anyone managing a fleet of Macbooks piled up on crates in a data center just so the OSS community can build their stuff ;-p

That's beside the point, though. 
I guess the real question here is: do you feel that the following trade is a fair one: a 5 MB jar that you can run from anywhere *provided your environment is setup properly* for a 50 MB installer that may require privileges to deploy but avoid  having to worry about such things?

I realize there's no right or wrong answer here, I'm just trying to get a feel of what would people expect/be less frustrated by.

**Comment by fthevenet** [comment]
In the mean time, I updated the front page and the wiki to make the JavaFX dependency more obvious, as well as the fact that it usually isn't bundled with OpenJDK builds (though it is with Oracle's JRE).

**Comment by Arkanosis** [comment]
Awesome! :+1:

**Comment by fthevenet** [comment]
Thanks!
It turned out to be pretty damn simple  after all: just defer the entry point into a different class (with no javafx.* import), in which you'd try to load the javafx.application.Application class via reflection.
This triggers the loading of the said class to be late enough to allow catching a potential ClassNotFoundException, therefore detecting that JavaFX is not present and allowing to react accordingly.

But sometimes the simplest solutions are the ones that elude you for the longest time...
