### ISSUE TITLE
Error when adding a JRDS source without protocol prefix

### ISSUE THREAD

**Issue by Arkanosis** [fthevenet/binjr#23]
Using binjr 1.4.1-SNAPSHOT, afb1ca3.

When I try to add a JRDS source with URI “localhost:8080” instead of “http://localhost:8080” I get a popup with the following error message:
```
IO Error while communicating with host "null:-1"
```
… then the popup slowly fades out and nothing more happens.

I have two suggestions:
 - [ ] prevent error popups from fading out (IMHO, it makes it uselessly hard to read the error message and copy it in a bug report);
 - [ ] allow HOST:PORT and HOST as alternatives to a full URI (default protocol would be HTTP and default PORT would be 80, as it's what most people would expect, I guess).

Thanks!

**Comment by fthevenet** [comment]
What I plan to do after reviewing your suggestion is:

- Make the duration after which popups automatically fade away configurable (including 'never')
- Move the URI validity check earlier on so that it fails while the user is still focused on the source selection dialogue box, and offer a clearer error message.

Not sure I will try defaulting the protocol, port etc... if it is not provided as I'm not overly keen on writing that kind of code myself. 
What should probably done however is to make the JRDS adapter use a  java.net.URL instead of a  java.net.URI as it probably makes more sense anyway. Maybe this this class is capable of making assumption when protocol and port are missing (I need to check) but in any case it should make it easier to provided a useful message in the event of a malformed URL.

**Comment by fthevenet** [comment]
Fixed in v1.4.1
